name: CI tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - run: npx browserslist@latest --update-db
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
    - run: npm install
    - run: export APPLITOOLS_API_KEY="OloyoDOU8S3wkDKOT732lBVxn39fhC2rmNc7103Yu626Y110"
    - run: APPLITOOLS_API_KEY="OloyoDOU8S3wkDKOT732lBVxn39fhC2rmNc7103Yu626Y110" npx cypress open
    
    
