name: CI tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
    - run: npm start
    - run: npx browserslist@latest --update-db
    - run: APPLITOOLS_API_KEY=\"OloyoDOU8S3wkDKOT732lBVxn39fhC2rmNc7103Yu626Y110\" npx cypress open
    
    
